### PR TITLE
Mark v2.2.0 for release

### PR DESCRIPTION
**Pull request by nicksay**

### CODE REVIEW

**Comment by DavidCPhillips** [comment]
LGTM

Do we have release notes anywhere? Anywhere other than the commit log that is.

**Comment by nicksay** [comment]
Right now, it's just https://github.com/youtube/spfjs/releases.  Perhaps they would be a good addition to the website though?

**Comment by DavidCPhillips** [comment]
Yeah I think it would be nice to see on the website. That's where I'd imagine people would go first for new info.

**Comment by nicksay** [comment]
Tracked as #324

**Pull request merged**
