### PR TITLE
Demo: Improve animation performance.

### PR DESCRIPTION
**Pull request by nicksay**
- Use GPU-accelerated properties when animating.
- Make minor overall style adjustments.

### CODE REVIEW

**Comment by awbraunstein** [comment]
Does this include that jank fix?

**Comment by nicksay** [comment]
Yes, the previous version had `top: 5%`, and that value was subtly changing during the content reparenting.  I changed it to `top: 2em`, which stays fixed.

**Comment by awbraunstein** [comment]
lgtm

**Comment by nicksay** [comment]
Post-commit associating this with #299.

**Pull request merged**
