### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by amZotti**

### CODE REVIEW

**Comment by rviscomi** [comment]
There are a few other places that reference 2016: https://github.com/youtube/spfjs/search?utf8=%E2%9C%93&q=2016

@nicksay ok to update all references?

**Comment by nicksay** [comment]
Happy New Year!

You can update `src/license.js`, `LICENSE`, and `README.md`.

Thanks for the PR!

**Comment by amZotti** [comment]
Great, I will update this PR now

**Comment by amZotti** [comment]
@nicksay Ok, done.

**Pull request merged**
